# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build AzCopy for M1 Mac

on:
  workflow_dispatch:
    inputs:
      m1_url:
        description: 'Target object in storage without SAS'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: macos-14
    environment: Release
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'

      - name: Build
        run: |
          mkdir -p output
         CGO_ENABLED=1 go build -o output/azcopy_darwin_arm64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: output/

      # - name: Azure Login
      #   uses: Azure/login@v2.1.0
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                
      # - name: Upload to AzCopy to M1 container
      #   run: AZCOPY_AUTO_LOGIN_TYPE=AzCLI ./azcopy_darwin_arm64 copy "azcopy_darwin_arm64" "${{ inputs.m1_url }}"
